# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculadora.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculadora.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x63\x61lculadora.proto\"\x14\n\x03Num\x12\r\n\x05value\x18\x01 \x01(\x02\"*\n\x08\x64oisNums\x12\x0e\n\x06value1\x18\x01 \x01(\x02\x12\x0e\n\x06value2\x18\x02 \x01(\x02\x32\xc9\x01\n\x0b\x43\x61lculadora\x12\x19\n\x04soma\x12\t.doisNums\x1a\x04.Num\"\x00\x12\x18\n\x03sub\x12\t.doisNums\x1a\x04.Num\"\x00\x12\x1a\n\x05multi\x12\t.doisNums\x1a\x04.Num\"\x00\x12\x18\n\x03\x64iv\x12\t.doisNums\x1a\x04.Num\"\x00\x12\x19\n\traiz_quad\x12\x04.Num\x1a\x04.Num\"\x00\x12\x18\n\x03\x65xp\x12\t.doisNums\x1a\x04.Num\"\x00\x12\x1a\n\x05resto\x12\t.doisNums\x1a\x04.Num\"\x00\x62\x06proto3'
)




_NUM = _descriptor.Descriptor(
  name='Num',
  full_name='Num',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Num.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=41,
)


_DOISNUMS = _descriptor.Descriptor(
  name='doisNums',
  full_name='doisNums',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value1', full_name='doisNums.value1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value2', full_name='doisNums.value2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['Num'] = _NUM
DESCRIPTOR.message_types_by_name['doisNums'] = _DOISNUMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Num = _reflection.GeneratedProtocolMessageType('Num', (_message.Message,), {
  'DESCRIPTOR' : _NUM,
  '__module__' : 'calculadora_pb2'
  # @@protoc_insertion_point(class_scope:Num)
  })
_sym_db.RegisterMessage(Num)

doisNums = _reflection.GeneratedProtocolMessageType('doisNums', (_message.Message,), {
  'DESCRIPTOR' : _DOISNUMS,
  '__module__' : 'calculadora_pb2'
  # @@protoc_insertion_point(class_scope:doisNums)
  })
_sym_db.RegisterMessage(doisNums)



_CALCULADORA = _descriptor.ServiceDescriptor(
  name='Calculadora',
  full_name='Calculadora',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=88,
  serialized_end=289,
  methods=[
  _descriptor.MethodDescriptor(
    name='soma',
    full_name='Calculadora.soma',
    index=0,
    containing_service=None,
    input_type=_DOISNUMS,
    output_type=_NUM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='sub',
    full_name='Calculadora.sub',
    index=1,
    containing_service=None,
    input_type=_DOISNUMS,
    output_type=_NUM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='multi',
    full_name='Calculadora.multi',
    index=2,
    containing_service=None,
    input_type=_DOISNUMS,
    output_type=_NUM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='div',
    full_name='Calculadora.div',
    index=3,
    containing_service=None,
    input_type=_DOISNUMS,
    output_type=_NUM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='raiz_quad',
    full_name='Calculadora.raiz_quad',
    index=4,
    containing_service=None,
    input_type=_NUM,
    output_type=_NUM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='exp',
    full_name='Calculadora.exp',
    index=5,
    containing_service=None,
    input_type=_DOISNUMS,
    output_type=_NUM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='resto',
    full_name='Calculadora.resto',
    index=6,
    containing_service=None,
    input_type=_DOISNUMS,
    output_type=_NUM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULADORA)

DESCRIPTOR.services_by_name['Calculadora'] = _CALCULADORA

# @@protoc_insertion_point(module_scope)
